"""initial migration

Revision ID: 23fc58d9eadd
Revises: 
Create Date: 2021-08-31 11:23:09.228500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fc58d9eadd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=64)))
    op.add_column('users', sa.Column('level', sa.Integer()))
    op.alter_column('users', 'reg_number',
               existing_type=sa.VARCHAR(length=16))
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_level'), 'users', ['level'], unique=False)
    op.create_index(op.f('ix_users_reg_number'), 'users', ['reg_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reg_number'), table_name='users')
    op.drop_index(op.f('ix_users_level'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.alter_column('users', 'reg_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.drop_column('users', 'passport')
    op.drop_column('users', 'level')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
